version: '3.8'
services:
  autopdf:
    build: .
    environment:
      - GLPI_URL=https://ltimindtree.in1.glpi-network.cloud  # YOUR GLPI URL
      - GLPI_APP_TOKEN=bnVEfEQ6n7kYpzFCEiF1UgCCWJkd5bWyU7UiQXd3   # YOUR APP TOKEN
      - GLPI_USER_TOKEN=hN04d5lgFrkmprGz183sPfUhXt04102DF10pUFsN   # YOUR USER TOKEN
